package com.demo.cms.entity;

import java.util.Date;

public class PrizeHistory {
	private Long id;

	private Long userId;

	private Long prizeId;

	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column user.createTime
	 *
	 * @return the value of user.createTime
	 *
	 * @mbggenerated Mon Aug 29 21:59:00 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column user.createTime
	 *
	 * @param createTime
	 *            the value for user.createTime
	 *
	 * @mbggenerated Mon Aug 29 21:59:00 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getPrizeId() {
		return prizeId;
	}

	public void setPrizeId(Long prizeId) {
		this.prizeId = prizeId;
	}
}
